---
name: Deploy tatodrone demo to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "readme.md"
      - "demo/*"
      - "report.md"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: clone tatodrone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info

      - name: Upload tatodrone artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy tatodrone to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
